In [5111]:
pip install numpy

Requirement already satisfied: numpy in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.5.0)
Note: you may need to restart the kernel to use updated packages.

In [5112]:
import numpy as np

In [5113]:
n5=np.zeros((4,3))
print(n5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

In [5114]:
n3=np.array([12,34,56,778,8,8,8,8,545,4,44,65]).reshape(4,3)
print(n3)
print(np.argmin(n3))
print(np.argmax(n3))

[[ 12  34  56]
 [778   8   8]
 [  8   8 545]
 [  4  44  65]]
9
3

In [5115]:
arr=np.array([90,56,23,44,77,93])
arr.sort()
print(arr)

[23 44 56 77 90 93]

In [5116]:
arr1=np.array([90,56,23,44,77,93])
new=sorted(arr1)
print(arr1)
print(new)

[90 56 23 44 77 93]
[np.int64(23), np.int64(44), np.int64(56), np.int64(77), np.int64(90), np.int64(93)]

In [5117]:
arr2=np.array([90,56,23,44,77,93,45,67,89,80,45,34])
new1=sorted(arr2)
print(arr2)
print(new1)

[90 56 23 44 77 93 45 67 89 80 45 34]
[np.int64(23), np.int64(34), np.int64(44), np.int64(45), np.int64(45), np.int64(56), np.int64(67), np.int64(77), np.int64(80), np.int64(89), np.int64(90), np.int64(93)]

In [5118]:
arr3=np.array([90,56,23,44,77,93])
print(-np.sort(-arr3))

[93 90 77 56 44 23]

In [5119]:
arr4=np.array([90,56,23,44,77,93,87,45,67,89,45,67]).reshape(4,3)
print(arr4)
arr4.sort()
print(arr4)

[[90 56 23]
 [44 77 93]
 [87 45 67]
 [89 45 67]]
[[23 56 90]
 [44 77 93]
 [45 67 87]
 [45 67 89]]

In [5120]:
new=np.array([90,56,23,44,77,93])
print(np.where(new>50))

(array([0, 1, 4, 5]),)

In [5121]:
print(new[3])

44

In [5122]:
for i in new:
    print(i)

90
56
23
44
77
93

In [5123]:
for i in new:
    print(i/2)

45.0
28.0
11.5
22.0
38.5
46.5

In [5124]:
for i in np.nditer(arr4):
    print(i)

23
56
90
44
77
93
45
67
87
45
67
89

In [5125]:
new1=np.array([23,34,56,67,78,34,56,787,9,90,7,4,5,6,7,5]).reshape(4,4)
new1.sort()
print(new1)
print(np.where(new1>50))
new1.sort(axis=0)
print(new1)
print(np.argmax(new1,axis=0))
for i in np.nditer(new1):
    print(i)

[[ 23  34  56  67]
 [ 34  56  78 787]
 [  4   7   9  90]
 [  5   5   6   7]]
(array([0, 0, 1, 1, 1, 2]), array([2, 3, 1, 2, 3, 3]))
[[  4   5   6   7]
 [  5   7   9  67]
 [ 23  34  56  90]
 [ 34  56  78 787]]
[3 3 3 3]
4
5
6
7
5
7
9
67
23
34
56
90
34
56
78
787

In [5126]:
A=np.array([2,3,4,8])
B=np.array([4,5,6,8])
C=np.concatenate((A,B))
print(C)

[2 3 4 8 4 5 6 8]

In [5127]:
print(np.vstack((A,B)))

[[2 3 4 8]
 [4 5 6 8]]

In [5128]:
print(np.hstack((A,B)))

[2 3 4 8 4 5 6 8]

In [5129]:
C=np.array([2,3,4,5,6,7,8,4]).reshape(4,2)
print(np.hstack((new1,C)))

[[  4   5   6   7   2   3]
 [  5   7   9  67   4   5]
 [ 23  34  56  90   6   7]
 [ 34  56  78 787   8   4]]

In [5130]:
#Filtering and Random

In [5131]:
d=np.array([90,56,34,12,56,78,9,10])
filtered_array=d>30
print(filtered_array)

[ True  True  True False  True  True False False]

In [5132]:
new=d[filtered_array]
print(new)

[90 56 34 56 78]

In [5133]:
from numpy import random as rd

In [5134]:
print(rd.rand(10))

[0.07595172 0.96108954 0.75695647 0.90797701 0.5725283  0.98826584
 0.06105857 0.25247036 0.03637593 0.92627911]

In [5135]:
print(rd.randint(50))

44

In [5136]:
print(rd.randint(50 ,size=(6,3)))

[[22 44 16]
 [15  8 47]
 [40 15 18]
 [ 8 19 30]
 [31 10  3]
 [44  2 10]]

In [5137]:
print(rd.randint(50 ,size=20))

[35 18 28 45 12 19 12 49 41 35 12 43 40 17  6 46 24 10 30 38]

In [5138]:
print(rd.randint(1,6 ,size=10))#randint(Start,stop,size)

[4 5 2 5 2 3 3 4 1 2]

In [5139]:
arr=rd.randint(50,size=(4,2))
print(arr)
print(type(arr))

[[35 18]
 [43 17]
 [45 11]
 [31  7]]
<class 'numpy.ndarray'>

In [5140]:
#PANDAS

In [5141]:
import pandas as pd

In [5142]:
#Pandas Series

In [5143]:
ser1=pd.Series([90,40,50,60,70])
print(ser1)

0    90
1    40
2    50
3    60
4    70
dtype: int64

In [5144]:
rol=[23,45,67,89,84,71]
names=["dora","pink","chota","pika","shiv","ranji gunji"]
ser2=pd.Series(names,index=rol)
print(ser2)

23           dora
45           pink
67          chota
89           pika
84           shiv
71    ranji gunji
dtype: str

In [5145]:
df=pd.read_csv(r"C:\Users\Student\Downloads\dianulls.csv")
df.head()

   preg   plas  pres  skin   insu  mass   pedi   age            class
0     6  148.0  72.0    35    0.0  33.6  0.627  50.0  tested_positive
1     1   85.0  66.0    29    0.0  26.6  0.351  31.0  tested_negative
2     8  183.0  64.0     0    0.0  23.3  0.672  32.0  tested_positive
3     1   89.0  66.0    23   94.0  28.1  0.167  21.0  tested_negative
4     0  137.0  40.0    35  168.0  43.1  2.288  33.0  tested_positive

In [5146]:
df=pd.read_csv(r"C:\Users\Student\Downloads\Salary Data.csv")
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [5147]:
df=pd.read_csv(r"C:\Users\Student\Downloads\Salary Data.csv")
df.tail()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [5148]:
df=pd.read_csv(r"C:\Users\Student\Downloads\Salary Data.csv")
df.head(10)

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
5,29.0,Male,Bachelor's,Marketing Analyst,2.0,55000.0
6,42.0,Female,Master's,Product Manager,12.0,120000.0
7,31.0,Male,Bachelor's,Sales Manager,4.0,80000.0
8,26.0,Female,Bachelor's,Marketing Coordinator,1.0,45000.0
9,38.0,Male,PhD,Senior Scientist,10.0,110000.0

In [5149]:
df=pd.read_csv(r"C:\Users\Student\Downloads\Salary Data.csv")
df.head(20)

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
5,29.0,Male,Bachelor's,Marketing Analyst,2.0,55000.0
6,42.0,Female,Master's,Product Manager,12.0,120000.0
7,31.0,Male,Bachelor's,Sales Manager,4.0,80000.0
8,26.0,Female,Bachelor's,Marketing Coordinator,1.0,45000.0
9,38.0,Male,PhD,Senior Scientist,10.0,110000.0
10,29.0,Male,Master's,Software Developer,3.0,75000.0
11,48.0,Female,Bachelor's,HR Manager,18.0,140000.0
12,35.0,Male,Bachelor's,Financial Analyst,6.0,65000.0
13,40.0,Female,Master's,Project Manager,14.0,130000.0
14,27.0,Male,Bachelor's,Customer Service Rep,2.0,40000.0
15,44.0,Male,Bachelor's,Operations Manager,16.0,125000.0
16,33.0,Female,Master's,Marketing Manager,7.0,90000.0
17,39.0,Male,PhD,Senior Engineer,12.0,115000.0
18,25.0,Female,Bachelor's,Data Entry Clerk,0.0,35000.0
19,51.0,Male,Bachelor's,Sales Director,22.0,180000.0

In [5150]:
pip install  openpyxl

Requirement already satisfied: openpyxl in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [5151]:
import openpyxl

In [5152]:
df_exc=pd.read_excel(r"C:\Users\Student\Downloads\healthcare_dataset.xlsx")
print(df_exc.head())

            Name  Age  Gender Blood Type Medical Condition Date of Admission  \
0  Bobby JacksOn   30    Male         B-            Cancer        2024-01-31
1   LesLie TErRy   62    Male         A+           Obesity        2019-08-20
2    DaNnY sMitH   76  Female         A-           Obesity        2022-09-22
3   andrEw waTtS   28  Female         O+          Diabetes        2020-11-18
4  adrIENNE bEll   43  Female        AB+            Cancer        2022-09-19

             Doctor                    Hospital Insurance Provider  \
0     Matthew Smith             Sons and Miller         Blue Cross
1   Samantha Davies                     Kim Inc           Medicare
2  Tiffany Mitchell                    Cook PLC              Aetna
3       Kevin Wells  Hernandez Rogers and Vang,           Medicare
4    Kathleen Hanna                 White-White              Aetna

   Billing Amount  Room Number Admission Type Discharge Date   Medication  \
0    18856.281306          328         Urgent     2024-02-02  Paracetamol
1    33643.327287          265      Emergency     2019-08-26    Ibuprofen
2    27955.096079          205      Emergency     2022-10-07      Aspirin
3    37909.782410          450       Elective     2020-12-18    Ibuprofen
4    14238.317814          458         Urgent     2022-10-09   Penicillin

   Test Results
0        Normal
1  Inconclusive
2        Normal
3      Abnormal
4      Abnormal

In [5153]:
df_txt=pd.read_csv(r"C:\Users\Student\Documents\dianullsnew.txt")
print(df_txt.head())

   preg   plas  pres  skin   insu  mass   pedi   age            class
0     6  148.0  72.0    35    0.0  33.6  0.627  50.0  tested_positive
1     1   85.0  66.0    29    0.0  26.6  0.351  31.0  tested_negative
2     8  183.0  64.0     0    0.0  23.3  0.672  32.0  tested_positive
3     1   89.0  66.0    23   94.0  28.1  0.167  21.0  tested_negative
4     0  137.0  40.0    35  168.0  43.1  2.288  33.0  tested_positive

In [5154]:
df_txt=pd.read_csv(r"C:\Users\Student\Documents\dianullsnew.txt",sep=" ")
print(df_txt.head())

    preg,plas,pres,skin,insu,mass,pedi,age,class
0    6,148,72,35,0,33.6,0.627,50,tested_positive
1     1,85,66,29,0,26.6,0.351,31,tested_negative
2     8,183,64,0,0,23.3,0.672,32,tested_positive
3    1,89,66,23,94,28.1,0.167,21,tested_negative
4  0,137,40,35,168,43.1,2.288,33,tested_positive

In [5155]:
df_txt=pd.read_csv(r"C:\Users\Student\Downloads\GRADES.txt",sep=" ")
print(df_txt.head())

    Names Initials  SEM1  SEM2  SEM3 Grade
0     Joe        K   9.8  10.0   9.9    A+
1  Rajesh        M   8.9   9.1   9.3     A
2  Kissan        V   9.9   9.3   9.2     A
3    Mary        N   7.7   8.0   7.1     B
4    Jeen        K   9.8   9.1   9.9    A+

In [5156]:
df_txt=pd.read_csv(r"C:\Users\Student\Downloads\GRADES.txt")
print(df_txt.head())

  Names Initials SEM1 SEM2 SEM3 Grade
0                 Joe K 9.8 10 9.9 A+
1              Rajesh M 8.9 9.1 9.3 A
2              Kissan V 9.9 9.3 9.2 A
3                  Mary N 7.7 8 7.1 B
4               Jeen K 9.8 9.1 9.9 A+

In [5157]:
df_txt=pd.read_csv(r"C:\Users\Student\Downloads\GRADES.txt",sep=" ")
print(df_txt.head(40))

     Names Initials  SEM1  SEM2  SEM3 Grade
0      Joe        K   9.8  10.0   9.9    A+
1   Rajesh        M   8.9   9.1   9.3     A
2   Kissan        V   9.9   9.3   9.2     A
3     Mary        N   7.7   8.0   7.1     B
4     Jeen        K   9.8   9.1   9.9    A+
5      Raj        M   8.9   9.1   9.3     A
6   Hassan        V   9.9   9.0   9.2     A
7     Mari        N   7.7   8.0   7.1     B
8     Jess        K   9.8   9.1   9.9    A+
9   Rajini        M   7.0   9.1   9.3     A
10   Kiran        V   9.9   9.3   9.2     A
11    Maya        N   7.7   8.0   7.1     B
12   Jolin        K   9.8   9.1   9.9    A+
13    Riya        M   8.0   9.1   9.3     A
14    Sana        V   9.9   9.3   9.2     A
15    Mark        N   7.7   8.0   7.0     B

In [5158]:
df_txt.loc[7:12,['Names','SEM3']]#df.loc[row,column]

     Names  SEM3
7     Mari   7.1
8     Jess   9.9
9   Rajini   9.3
10   Kiran   9.2
11    Maya   7.1
12   Jolin   9.9

In [5159]:
df_txt.iloc[7:12,[2,4]]#df.iloc[row,column number is accepted not name]

    SEM1  SEM3
7    7.7   7.1
8    9.8   9.9
9    7.0   9.3
10   9.9   9.2
11   7.7   7.1

In [5160]:
df_txt.iloc[7:12,2:4]#df.iloc[row,column number is accepted not name]

    SEM1  SEM2
7    7.7   8.0
8    9.8   9.1
9    7.0   9.1
10   9.9   9.3
11   7.7   8.0

In [5161]:
df_exc=pd.read_excel(r"C:\Users\Student\Downloads\healthcare_dataset.xlsx")
print(df_exc.head(104))

               Name  Age  Gender Blood Type Medical Condition  \
0     Bobby JacksOn   30    Male         B-            Cancer
1      LesLie TErRy   62    Male         A+           Obesity
2       DaNnY sMitH   76  Female         A-           Obesity
3      andrEw waTtS   28  Female         O+          Diabetes
4     adrIENNE bEll   43  Female        AB+            Cancer
..              ...  ...     ...        ...               ...
99        MaRk foRD   18    Male         B+            Asthma
100   mARcUS ZAmorA   69    Male         O+         Arthritis
101     KaTiE hENry   70    Male         B+          Diabetes
102  wilLIAm morTON   21    Male         A+          Diabetes
103  KaTRina maRTin   47    Male         A-          Diabetes

    Date of Admission             Doctor                       Hospital  \
0          2024-01-31      Matthew Smith                Sons and Miller
1          2019-08-20    Samantha Davies                        Kim Inc
2          2022-09-22   Tiffany Mitchell                       Cook PLC
3          2020-11-18        Kevin Wells     Hernandez Rogers and Vang,
4          2022-09-19     Kathleen Hanna                    White-White
..                ...                ...                            ...
99         2022-10-18       Steven James                       Luna Inc
100        2021-11-13      Jeremiah Wolf  Hernandez, Ritter and Huffman
101        2022-07-08   Roberto Petersen                       Reed LLC
102        2023-06-25  Christina Hammond                Thompson-Walker
103        2019-07-09     Patricia Colon                   Group Nguyen

    Insurance Provider  Billing Amount  Room Number Admission Type  \
0           Blue Cross    18856.281306          328         Urgent
1             Medicare    33643.327287          265      Emergency
2                Aetna    27955.096079          205      Emergency
3             Medicare    37909.782410          450       Elective
4                Aetna    14238.317814          458         Urgent
..                 ...             ...          ...            ...
99    UnitedHealthcare    28837.677053          227       Elective
100              Cigna    25425.727863          115       Elective
101              Aetna     7187.272346          402      Emergency
102   UnitedHealthcare     3125.736477          442         Urgent
103           Medicare    31516.100734          418       Elective

    Discharge Date   Medication  Test Results
0       2024-02-02  Paracetamol        Normal
1       2019-08-26    Ibuprofen  Inconclusive
2       2022-10-07      Aspirin        Normal
3       2020-12-18    Ibuprofen      Abnormal
4       2022-10-09   Penicillin      Abnormal
..             ...          ...           ...
99      2022-11-11      Aspirin      Abnormal
100     2021-11-21      Aspirin        Normal
101     2022-07-25      Aspirin        Normal
102     2023-07-11    Ibuprofen        Normal
103     2019-08-05   Penicillin  Inconclusive

[104 rows x 15 columns]

In [5162]:
df_exc.iloc[70:101,1:5]

     Age  Gender Blood Type Medical Condition
70    29  Female         O+            Cancer
71    18    Male         A-           Obesity
72    24    Male        AB-            Cancer
73    27    Male        AB-          Diabetes
74    57  Female        AB-         Arthritis
75    74  Female         A+         Arthritis
76    22  Female         A-         Arthritis
77    33  Female         B-          Diabetes
78    57    Male         B+         Arthritis
79    61    Male         B+            Cancer
80    20    Male         O+         Arthritis
81    67    Male        AB+      Hypertension
82    80  Female        AB-          Diabetes
83    44    Male         O+           Obesity
84    26  Female         B-            Asthma
85    80    Male        AB+            Cancer
86    63    Male         B-            Asthma
87    58  Female         B-         Arthritis
88    38  Female         A+            Cancer
89    60    Male         B+      Hypertension
90    49    Male         B+            Cancer
91    80    Male         A+          Diabetes
92    35  Female         B+          Diabetes
93    84    Male         A+            Asthma
94    76    Male         A+          Diabetes
95    79  Female         A-      Hypertension
96    76  Female         O+          Diabetes
97    55  Female         A+          Diabetes
98    53    Male         B-            Cancer
99    18    Male         B+            Asthma
100   69    Male         O+         Arthritis

In [5163]:
df_txt['Avg_Score']=((df_txt['SEM1']+df_txt['SEM2']+df_txt['SEM3'])/3)
df_txt.head()

    Names Initials  SEM1  SEM2  SEM3 Grade  Avg_Score
0     Joe        K   9.8  10.0   9.9    A+   9.900000
1  Rajesh        M   8.9   9.1   9.3     A   9.100000
2  Kissan        V   9.9   9.3   9.2     A   9.466667
3    Mary        N   7.7   8.0   7.1     B   7.600000
4    Jeen        K   9.8   9.1   9.9    A+   9.600000

In [5164]:
df_txt['Full_name']=(df_txt['Initials']+" " +df_txt['Names'])
df_txt.head()

    Names Initials  SEM1  SEM2  SEM3 Grade  Avg_Score Full_name
0     Joe        K   9.8  10.0   9.9    A+   9.900000     K Joe
1  Rajesh        M   8.9   9.1   9.3     A   9.100000  M Rajesh
2  Kissan        V   9.9   9.3   9.2     A   9.466667  V Kissan
3    Mary        N   7.7   8.0   7.1     B   7.600000    N Mary
4    Jeen        K   9.8   9.1   9.9    A+   9.600000    K Jeen

In [5165]:
del df_txt['Names']
df_txt.head()

  Initials  SEM1  SEM2  SEM3 Grade  Avg_Score Full_name
0        K   9.8  10.0   9.9    A+   9.900000     K Joe
1        M   8.9   9.1   9.3     A   9.100000  M Rajesh
2        V   9.9   9.3   9.2     A   9.466667  V Kissan
3        N   7.7   8.0   7.1     B   7.600000    N Mary
4        K   9.8   9.1   9.9    A+   9.600000    K Jeen

In [5166]:
df_txt.drop("Initials",axis=1)
df_txt.head()

  Initials  SEM1  SEM2  SEM3 Grade  Avg_Score Full_name
0        K   9.8  10.0   9.9    A+   9.900000     K Joe
1        M   8.9   9.1   9.3     A   9.100000  M Rajesh
2        V   9.9   9.3   9.2     A   9.466667  V Kissan
3        N   7.7   8.0   7.1     B   7.600000    N Mary
4        K   9.8   9.1   9.9    A+   9.600000    K Jeen

In [5167]:
df_txt.drop("Initials",axis=1,inplace=True)
df_txt.head()

   SEM1  SEM2  SEM3 Grade  Avg_Score Full_name
0   9.8  10.0   9.9    A+   9.900000     K Joe
1   8.9   9.1   9.3     A   9.100000  M Rajesh
2   9.9   9.3   9.2     A   9.466667  V Kissan
3   7.7   8.0   7.1     B   7.600000    N Mary
4   9.8   9.1   9.9    A+   9.600000    K Jeen